apiVersion: v1
kind: Service
metadata:
  name: aiops-frontend-svc
  labels:
    app: frontend-svc
    component: aiops
  namespace: aiops
spec:
  type: NodePort
  selector:
    matchLabels:
      app: frontend
      component: aiops
  ports:
    - port: 80
      targetPort: web
      protocol: TCP