apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiops-backend
  labels:
    component: aiops
    app: backend
  namespace: aiops
spec:
  replicas: 1
  selector:
    matchLabels:
      component: aiops
      app: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: aiops-backend
      labels:
        component: aiops
        app: backend

    spec:
      containers:
      - name: aiops-backend-container
        image: 
        ports:
        - name: server
          containerPort: 8081
        - name: matrics
          containerPort: 9001
        env:
        - name: DB_PORT
          value: "3306"
        - name: DB_HOST
          value: "mysql-svc"
        - name: DB_USER
          value: "aiops"
        - name: DB_PASSWORD
          value: "123456"
        - name: DB_NAME
          value: "aiops"
        - name: REDIS_HOST
          value: "redis-svc"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: "123456"
        resources:
          limits:
            memory: 1Gi
            cpu: 1000m
          requests:
            memory: 512Mi
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

      