apiVersion: v1
kind: Service
metadata:
  name: aiops-backend-svc
  labels:
    app: backend-svc
    component: aiops
  namespace: aiops
spec:
  selector:
    app: backend
    component: aiops
  type: ClusterIP
  ports:
  - name: server
    port: 8081
    targetPort: server
    protocol: TCP
  - name: matrics
    port: 9001
    targetPort: matrics
    protocol: TCP